
export const REQUEST_USERS_LIST = 'REQUEST_USERS_LIST';
export const REQUEST_USERS_SUCCESS = 'REQUEST_USERS_SUCCESS';
export const REQUEST_USERS_FAILED = 'REQUEST_USERS_FAILED';
export const REQUEST_ALBUMS_LIST = 'REQUEST_ALBUMS_LIST';
export const REQUEST_ALBUMS_SUCCESS = 'REQUEST_ALBUMS_SUCCESS';
export const REQUEST_ALBUMS_FAILED = 'REQUEST_ALBUMS_FAILED';
export const REQUEST_POSTS_LIST = 'REQUEST_POSTS_LIST';
export const REQUEST_POSTS_SUCCESS = 'REQUEST_POSTS_SUCCESS';
export const REQUEST_POSTS_FAILED = 'REQUEST_POSTS_FAILED';
export const REQUEST_COMMENTS_LIST = 'REQUEST_COMMENTS_LIST';
export const REQUEST_COMMENTS_SUCCESS = 'REQUEST_COMMENTS_SUCCESS';
export const REQUEST_COMMENTS_FAILED = 'REQUEST_COMMENTS_FAILED';