
export const REQUEST_USERS_LIST = 'REQUEST_USERS_LIST';
export const REQUEST_USERS_SUCCESS = 'REQUEST_USERS_SUCCESS';
export const REQUEST_USERS_FAILED = 'REQUEST_USERS_FAILED';
export const REQUEST_ALBUMS_LIST = 'REQUEST_ALBUMS_LIST';
export const REQUEST_ALBUMS_SUCCESS = 'REQUEST_ALBUMS_SUCCESS';
export const REQUEST_ALBUMS_FAILED = 'REQUEST_ALBUMS_FAILED';